spring.application.name=unicheck

spring.datasource.url=jdbc:postgresql://localhost:5432/unicheck
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate