spring.application.name=sistema_agendamento

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_agendamento
spring.datasource.username=seu_banco
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate